# Generated by Django 5.0 on 2023-12-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationprofile',
            old_name='phone_number',
            new_name='phone_company',
        ),
        migrations.AddField(
            model_name='registrationprofile',
            name='nid_passport',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationprofile',
            name='phone_personal',
            field=models.CharField(default='defalut', max_length=20),
            preserve_default=False,
        ),
    ]
