# Generated by Django 5.0 on 2023-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_phone_number_registrationprofile_phone_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
