"""
Django settings for NRB_api_backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b2ce(&e53&ou#m(8zaj&-fu84a5u_mez1=dt#duoz1_efs%g3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_management',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'NRB_api_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NRB_api_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql',
#     'NAME': 'nrb',
#     'USER': 'Jayed',
#     'PASSWORD': 'PuoDXghkd9F6',
#     'HOST': 'ep-red-lab-91575302.ap-southeast-1.aws.neon.tech',
#     'PORT': '5432',
#     'OPTIONS': {'sslmode': 'require'},
#   }
# }

DATABASES = { #This is Server Database with REMOTE HOST (Not as fast as LOCALLY HOSTED SERVER ONE)
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tanvirah_NRB',
        'USER': 'tanvirah_tanvir',
        'PASSWORD': 'tanvir@12345',
        'HOST': '65.109.69.35',  # Remote MySQL host (IP or domain)
        'PORT': '3306',  # MySQL default port
    }
}

# DATABASES = {
# This is Server Database with REMOTE HOST (Not as fast as LOCALLY HOSTED SERVER ONE)
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'tanvirah_NRB',
#         'USER': 'tanvirah_tanvir',
#         'PASSWORD': 'tanvir@12345',
#         'HOST': 'localhost',  # Remote MySQL host (IP or domain)
#         'PORT': '3306',  # MySQL default port
#     }
# }

# DATABASES = {
#     #This is the Server Database With Locally Hosted and the FASTEST ONE.
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'tanvirah_NRB',
#         'USER': 'tanvirah_tanvir',
#         'PASSWORD': 'tanvir@12345',
#         'HOST': 'localhost',  # Remote MySQL host (IP or domain)
#         'PORT': '3306',  # MySQL default port
#     }
# }



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'NRB',
#         'USER': 'postgres',
#         'PASSWORD': '12345',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# custom SSSSSSSSSSSSSSS
AUTH_USER_MODEL = 'user_management.CustomUser'
# custom EEEEEEEEEEEEEEE

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.ipsitasoft.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'noreply@ipsitasoft.com'
EMAIL_HOST_PASSWORD = 'noP@#2023'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
